package DAO;
// Generated 11-may-2023 20:42:16 by Hibernate Tools 4.3.1



/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private String apellidos;
     private String password;
     private String direccion;
     private int telefono;

    public Clientes() {
    }

    public Clientes(String dni, String nombre, String apellidos, String password, String direccion, int telefono) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.password = password;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }




}


