package DAO;
// Generated 11-may-2023 20:42:16 by Hibernate Tools 4.3.1



/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private Integer id;
     private int numeroCuenta;
     private String iban;
     private int saldo;
     private String divisa;

    public Cuenta() {
    }

    public Cuenta(int numeroCuenta, String iban, int saldo, String divisa) {
       this.numeroCuenta = numeroCuenta;
       this.iban = iban;
       this.saldo = saldo;
       this.divisa = divisa;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getNumeroCuenta() {
        return this.numeroCuenta;
    }
    
    public void setNumeroCuenta(int numeroCuenta) {
        this.numeroCuenta = numeroCuenta;
    }
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }
    public int getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(int saldo) {
        this.saldo = saldo;
    }
    public String getDivisa() {
        return this.divisa;
    }
    
    public void setDivisa(String divisa) {
        this.divisa = divisa;
    }




}


