package DAO;
// Generated 11-may-2023 20:42:16 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private Integer idPrestamo;
     private String tipoPrestamo;
     private int numeroPrestamo;
     private Date fechaConstitucion;
     private Date fechaCancelacion;
     private double capitalConcedido;
     private int plazos;

    public Prestamo() {
    }

    public Prestamo(String tipoPrestamo, int numeroPrestamo, Date fechaConstitucion, Date fechaCancelacion, double capitalConcedido, int plazos) {
       this.tipoPrestamo = tipoPrestamo;
       this.numeroPrestamo = numeroPrestamo;
       this.fechaConstitucion = fechaConstitucion;
       this.fechaCancelacion = fechaCancelacion;
       this.capitalConcedido = capitalConcedido;
       this.plazos = plazos;
    }
   
    public Integer getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(Integer idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public String getTipoPrestamo() {
        return this.tipoPrestamo;
    }
    
    public void setTipoPrestamo(String tipoPrestamo) {
        this.tipoPrestamo = tipoPrestamo;
    }
    public int getNumeroPrestamo() {
        return this.numeroPrestamo;
    }
    
    public void setNumeroPrestamo(int numeroPrestamo) {
        this.numeroPrestamo = numeroPrestamo;
    }
    public Date getFechaConstitucion() {
        return this.fechaConstitucion;
    }
    
    public void setFechaConstitucion(Date fechaConstitucion) {
        this.fechaConstitucion = fechaConstitucion;
    }
    public Date getFechaCancelacion() {
        return this.fechaCancelacion;
    }
    
    public void setFechaCancelacion(Date fechaCancelacion) {
        this.fechaCancelacion = fechaCancelacion;
    }
    public double getCapitalConcedido() {
        return this.capitalConcedido;
    }
    
    public void setCapitalConcedido(double capitalConcedido) {
        this.capitalConcedido = capitalConcedido;
    }
    public int getPlazos() {
        return this.plazos;
    }
    
    public void setPlazos(int plazos) {
        this.plazos = plazos;
    }




}


