package DAO;
// Generated 11-may-2023 20:42:16 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta  implements java.io.Serializable {


     private Integer idTarjeta;
     private int numeroTarjeta;
     private Date fechaCaducidad;
     private int cvv;
     private String tipoTarjeta;

    public Tarjeta() {
    }

    public Tarjeta(int numeroTarjeta, Date fechaCaducidad, int cvv, String tipoTarjeta) {
       this.numeroTarjeta = numeroTarjeta;
       this.fechaCaducidad = fechaCaducidad;
       this.cvv = cvv;
       this.tipoTarjeta = tipoTarjeta;
    }
   
    public Integer getIdTarjeta() {
        return this.idTarjeta;
    }
    
    public void setIdTarjeta(Integer idTarjeta) {
        this.idTarjeta = idTarjeta;
    }
    public int getNumeroTarjeta() {
        return this.numeroTarjeta;
    }
    
    public void setNumeroTarjeta(int numeroTarjeta) {
        this.numeroTarjeta = numeroTarjeta;
    }
    public Date getFechaCaducidad() {
        return this.fechaCaducidad;
    }
    
    public void setFechaCaducidad(Date fechaCaducidad) {
        this.fechaCaducidad = fechaCaducidad;
    }
    public int getCvv() {
        return this.cvv;
    }
    
    public void setCvv(int cvv) {
        this.cvv = cvv;
    }
    public String getTipoTarjeta() {
        return this.tipoTarjeta;
    }
    
    public void setTipoTarjeta(String tipoTarjeta) {
        this.tipoTarjeta = tipoTarjeta;
    }




}


