package DAO;
// Generated 11-may-2023 20:42:16 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transferncia generated by hbm2java
 */
public class Transferncia  implements java.io.Serializable {


     private Integer idTransferencia;
     private int numeroTransferencia;
     private Date fechaEmision;
     private String cuentaOrigen;
     private String cuentaDestino;
     private int cantidad;
     private String concepto;

    public Transferncia() {
    }

    public Transferncia(int numeroTransferencia, Date fechaEmision, String cuentaOrigen, String cuentaDestino, int cantidad, String concepto) {
       this.numeroTransferencia = numeroTransferencia;
       this.fechaEmision = fechaEmision;
       this.cuentaOrigen = cuentaOrigen;
       this.cuentaDestino = cuentaDestino;
       this.cantidad = cantidad;
       this.concepto = concepto;
    }
   
    public Integer getIdTransferencia() {
        return this.idTransferencia;
    }
    
    public void setIdTransferencia(Integer idTransferencia) {
        this.idTransferencia = idTransferencia;
    }
    public int getNumeroTransferencia() {
        return this.numeroTransferencia;
    }
    
    public void setNumeroTransferencia(int numeroTransferencia) {
        this.numeroTransferencia = numeroTransferencia;
    }
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }
    public String getCuentaOrigen() {
        return this.cuentaOrigen;
    }
    
    public void setCuentaOrigen(String cuentaOrigen) {
        this.cuentaOrigen = cuentaOrigen;
    }
    public String getCuentaDestino() {
        return this.cuentaDestino;
    }
    
    public void setCuentaDestino(String cuentaDestino) {
        this.cuentaDestino = cuentaDestino;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }




}


